[rtc]
id=1
name=RTC
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
set_rtc_time=0
state=2

[serial]
id=2
name="串口"
ignore_tty=ttyFIQ0_ttyS0
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[TFcard]
id=3
name="TF卡"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[BT]
id=4
name="蓝牙"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[WIFI]
id=5
name="WIFI"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[ethernet]
id=6
name="以太网"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[4G]
id=6
name="4G"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

#下面是手动测试项
[deviceInfo]
id=7
name="设备信息"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[RGB]
id=8
name="RGB"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[pwm]
id=9
name="PWM/背光"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[tp]
id=10
name="触摸"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[soundCard]
id=11
name="声卡"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[led]
id=12
name="补光灯"
bl_led_ctl="/proc/rp_gpio/bl_led"
ir_led_ctl="/proc/rp_gpio/ir_led"
enable=0
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[USB]
id=13
name="USB"
enable=1
power_gpios=gpio2b1_gpio2b2_gpio2b3_gpio2a4_gpio2a6_gpio4c5_gpio4d1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[camera]
id=14
name="摄像头"
camera1="/dev/video0"
camera2="/dev/video5"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[ADC]
id=15
name="ADC按键"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[GPIO]
id=16
name="GPIO"
enable=1
#ignore_gpios="gpio2b4_gpio1c4_gpio1b2_gpio1a3_gpio0b4", #ignore gpios will not be control
ignore_gpios=""
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[NPU]
id=16
name="NPU"
enable=0
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[stress]
id=17
name="stress"
enable=1
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

[wifiStress]
id=18
name="WIFI压力"
enable=0
#用于永久保存测试状态，0表示失败，1表示成功，2表示未测试
state=2

