#!/bin/sh

#
# Start the 4G-daemon
#

case "$1" in
  start)
	printf "Starting 4G-daemon: "
	/usr/bin/4G-daemon &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping 4G-daemon: "
	killall 4G-daemon
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
